//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kondidat
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Pasport { get; set; }
        public string INN { get; set; }
        public string Obrazov { get; set; }
        public Nullable<int> Dolg { get; set; }
    
        public virtual Dolg Dolg1 { get; set; }
    }
}
