//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Otdel_KadrovEntities : DbContext
    {
        public Otdel_KadrovEntities()
            : base("name=Otdel_KadrovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolnich> Bolnich { get; set; }
        public virtual DbSet<Dolg> Dolg { get; set; }
        public virtual DbSet<Komandirovka> Komandirovka { get; set; }
        public virtual DbSet<Kondidat> Kondidat { get; set; }
        public virtual DbSet<Sotrud> Sotrud { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uvolnenie> Uvolnenie { get; set; }
    }
}
